### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Sheradil** [eowjd0512/fisheye-calib-adapter#2]
Hey,

first of all, thanks for this repository. I was looking for something like this for a long time and found it by accident.

I get a segmentation fault when I change the output model inside of the config.yml to OcamCalib and run
 `./main example/config.yml`

Anything I can do about it?

**Comment by eowjd0512** [comment]
Hello Sheradil,

First of all, thank you for taking an interest in my repository. I'm really happy that it has been helpful to you.

I have confirmed once again that changing the output model to OCamCalib in my PC environment does not cause a segmentation fault and that it runs normally. I also confirmed that it works in a docker environment.

Here are the results from my terminal.

![image](https://github.com/user-attachments/assets/3d784bf7-edcf-4dd1-b00d-e115d4ab0dcf)

Could I possibly see the logs where the segmentation fault occurs?

Since the code is not complex, if you could run debugging and tell me where it crashes, it would be easier for me to check.

**Comment by Sheradil** [comment]
Hey,

took some time ... My system was newly setup 2 weeks ago and I had to reinstall code and the extensions to debug within VSCode in a docker container. 

So, I rebuild the program inside the container and I still have the same issue.

But with the debugger I managed to find the problem on my own.
I made a small mistake.

I looked at the Supported Camera Models and copy pasted "OCamCalib" to the example config file. 
In your code you just check for "OcamCalib" which then results in a SegFault in adapter.adapt()
Not sure why the error message didn't show up before. I just got the error message now inside VSCode.
Probably change the name in the supported camera models.

Now I just have to hope that I am able to adapt your code to our modified OCamCalib model.
